using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using NUnit.Framework;
using TestGeneratorLib;

namespace Tests
{
    [TestFixture]
    public class TestGeneratorLibTests
    {
        public List<string> testcodeLines;
        [SetUp]
        public void Init()
        {
            testcodeLines = SingleFileContentTestGenerator.GenerateTestFile
                                    (new Tuple<string, List<string>>
                                    ("test", File.ReadAllLines(@"D:\”Õ» \5 ÒÂÏ\MPP(SPP)\mpp_4\mpp_4\bin\Debug\netcoreapp3.1\src\Writer.cs")
                                    .ToList()));
        }
        [Test]
        public void TestAddingUsings_CodeLines_ReturnsUsingStatement()
        {
            var expected = "using System;";
            var received = testcodeLines[0];
            Assert.AreEqual(expected, received);
        }

        [Test]
        public void TestAddingAttributes_CodeLines_ReturnsTrueIfFoind()
        {

            Assert.IsTrue((testcodeLines.Contains("\t[TestFixture]")) && (testcodeLines.Contains("\t\t[Test]")));
        }

        [Test]
        public void TestAddingTestClassName_CodeLines_ReturnsTestClassName()
        {

            var expected = "public class WriterTests";
            string received ="" ;
            foreach(var line in testcodeLines)
            {
                if(line.Contains("WriterTests"))
                {
                    received = line.Substring(0,line.Length-1).Trim();
                    break;
                }
            }
            Assert.AreEqual(expected, received);
        }

        [Test]
        public void TestAddingTestMethodName_CodeLines_ReturnsTestMethodName()
        {

            var expected = "public void WriteTest()";
            string received = "";
            foreach (var line in testcodeLines)
            {
                if (line.Contains("WriteTest()"))
                {
                    received = line.Substring(0, line.Length - 1).Trim();
                    break;
                }
            }
            Assert.AreEqual(expected, received);
        }

        [Test]
        public void TestAddingTestAssert_CodeLines_ReturnsTestAssertString()
        {

            var expected = "Assert.Fail(\"autogenerated\")";
            string received = "";
            foreach (var line in testcodeLines)
            {
                if (line.Contains("Assert"))
                {
                    received = line.Substring(0, line.Length - 1).Trim();
                    break;
                }
            }
            Assert.AreEqual(expected, received);
        }
    }
}